# version: '3.8'


services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=http://ec2-13-61-184-107.eu-north-1.compute.amazonaws.com/api
    depends_on:
      - server
      - socket
    restart: unless-stopped



  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5000
    restart: unless-stopped


  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "8900:8900"
    environment:
      - PORT=8900
    depends_on:
      - server
    restart: unless-stopped