# version: '3.8'


services:
  client:
    build: ./client
    ports:
      - "80:80"
    environment:
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - server
      - socket
    restart: unless-stopped



  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5000
    restart: unless-stopped


  socket:
    build: ./socket
    ports:
      - "8900:8900"
    environment:
      - PORT=8900
    depends_on:
      - server
    restart: unless-stopped