version: '3.8'

services:
  client:
    # user: "node"
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
      - socket
    command: npm run start

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=5000
      - NODE_ENV=development
    restart: unless-stopped
    command: npm run start:dev

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile.dev
    ports:
      - "8901:8901"
    volumes:
      - ./socket:/app
      - /app/node_modules
    environment:
      - PORT=8901
      - NODE_ENV=development
    restart: unless-stopped
    command: npm run start:dev