# version: '3.8'


services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=/
      - REACT_APP_SOCKET_URL=/socket.io
      - REACT_APP_ENV=production
    depends_on:
      - server
      - socket
    restart: unless-stopped



  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - PORT=5000
      - CORS_ORIGIN=http://ec2-56-228-7-213.eu-north-1.compute.amazonaws.com
    restart: unless-stopped


  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "8900:8900"
    environment:
      - PORT=8900
      - CORS_ORIGIN=http://ec2-56-228-7-213.eu-north-1.compute.amazonaws.com
    depends_on:
      - server
    restart: unless-stopped